#!/usr/bin/env ruby
#^syntax detection

site 'http://community.opscode.com/api/v1'

cookbook "apt"

cookbook 'database',
  :git => 'https://github.com/finnlabs/cookbook-database.git',
  :ref => 'COOK-1401'

cookbook 'chiliproject',
  :git => 'https://github.com/meineerde/chiliproject-cookbook.git'

# cookbook 'chef-client'

# cookbook 'apache2', '>= 1.0.0'

# cookbook 'rvm',
#   :git => 'https://github.com/fnichol/chef-rvm'

# cookbook 'postgresql',
#   :git => 'https://github.com/findsyou/cookbooks',
#   :ref => 'postgresql-improvements'
