#!/usr/bin/env ruby
# -*- mode: ruby -*-
# vi: set ft=ruby :

site 'http://community.opscode.com/api/v1'

cookbook 'apt'

cookbook 'chiliproject',
  :git => 'https://github.com/chiliproject/cookbook.git'
